pipelines:
  default:
    - step:
        name: Build
        image: maven:3.6-jdk-11
        caches:
          - maven
        script:
          - mvn clean install deploy -s settings.xml
        artifacts:
          - restheart-platform-security/target/restheart-platform-security-*.zip
          - restheart-platform-security/target/restheart-platform-security.jar
          - restheart-platform-core/target/restheart-platform-core-*.zip
          - restheart-platform-core/target/restheart-platform-core.jar

