pipelines:
  branches:
    master:
      - step:
          name: Build and deploy
          image: maven:3.6-jdk-11
          caches:
            - maven
          script:
            - mvn clean install deploy -s settings.xml
          artifacts:
            - target/restheart-platform-security-*.zip
            - target/restheart-platform-security.jar
      - step:
          name: Upload to S3
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: "download.restheart.com"
                LOCAL_PATH: "target"
                DELETE_FLAG: "false"
                CONTENT_ENCODING: "UTF-8"
      - step:
          name: Invalidate CloudFront
          image: python:3.7-alpine
          caches:
            - pip
          script:
            - pip install awscli
            - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            - export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"
            - aws configure set preview.cloudfront true
            - aws cloudfront create-invalidation --distribution-id "E1WE8DOGKDF0SO" --paths "/*"
